# AYANAMI THEME - RE-EVOLVED PALETTE
GRADIENT_MODE="diagonal"
GRADIENT_COLORS=(
  "100,170,255"   # Azul Rei (Saturado)
  "255,40,40"     # Rojo Sangre/Ojos
  "140,190,255"   # Azul Claro
  "40,60,100"     # Azul Oscuro (Sombras/Plugsuit)
)
